import React from 'react';
import { forEach } from 'lodash';
import { ApolloClient } from 'apollo-client';
import { ApolloProvider } from '@apollo/react-hooks';
import { HttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { onError } from 'apollo-link-error';
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory';
import typeDefs from './typeDefs';
import resolvers from './resolvers';
import { GRAPHQL_URL } from './constants';

// TODO
// fragmentTypes.json generated by schemaQuery.js
// import introspectionQueryResultData from '../fragmentTypes.json';

const httpLink = new HttpLink({
    uri: GRAPHQL_URL
});

const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData: {
        __schema: {
            types: [],
        },
    },
    // TODO
    // introspectionQueryResultData
});

const cache = new InMemoryCache({
    fragmentMatcher
});

let initialSession = {
    __typename: 'Session'
};

// TODO
/*
if (loggedIn()) {
    const token = getToken();
    const session = getSession(token);
    initialSession = {
        ...session
    };
};
*/

cache.writeData({
    data: {
        session: initialSession,
    }
});

const errorLink = onError(({ networkError, graphQLErrors }) => {
    if (networkError) {
        // const { message, statusCode } = networkError;
        // TODO
    }
    if (graphQLErrors) {
        forEach(graphQLErrors, ({ message }) => {
            // TODO
        });
    }
});
  
const link = ApolloLink.from([
    errorLink,
    httpLink,
]);

const client = new ApolloClient({
    link,
    cache,
    typeDefs,
    resolvers
});

export default ({ children }) => (
    <ApolloProvider client={client}>
        {children}
    </ApolloProvider>
);